SELECT *
FROM FATTORINO;


SELECT DISTINCT AID
FROM CONSEGNA;


SELECT NOME, FID
FROM FATTORINO
WHERE NOME LIKE 'B%';


SELECT NOME, SESSO, FID
FROM FATTORINO
WHERE TEL <> 8467 OR TEL IS NULL;


SELECT NOME, CITTA
FROM FATTORINO, MULTE
WHERE FATTORINO.FID = MULTE.FID;


SELECT FATTORINO.NOME
FROM FATTORINO, CONSEGNA
WHERE (FATTORINO.CITTA = 'Inglewood' OR FATTORINO.CITTA = 'Stratford') AND FATTORINO.FID = CONSEGNA.FID
GROUP BY FATTORINO.FID, FATTORINO.NOME
HAVING COUNT(*) > 1;


SELECT FATTORINO.FID, SUM(MULTE.COSTO) AS TOT_COSTO
FROM FATTORINO, MULTE
WHERE FATTORINO.CITTA = 'Inglewood' AND FATTORINO.FID = MULTE.FID
GROUP BY FATTORINO.FID
HAVING COUNT(*) > 1;


SELECT FATTORINO.FID, FATTORINO.NOME, FATTORINO.INIZIALI
FROM FATTORINO
WHERE FATTORINO.FID NOT IN (SELECT MULTE.FID FROM MULTE);


SELECT FATTORINO.FID
FROM FATTORINO
WHERE FATTORINO.FID IN (SELECT MULTE.FID 
                        FROM MULTE 
                        WHERE MULTE.COSTO = 25)
      AND FATTORINO.FID IN (SELECT MULTE.FID 
                        FROM MULTE 
                        WHERE MULTE.COSTO = 30);


SELECT MAX(COUNT(*))
FROM MULTE
GROUP BY MULTE.FID, MULTE.DATA;


SELECT AVG(SUM(MULTE.COSTO))
FROM MULTE
GROUP BY MULTE.FID;


WITH A_F_TOT_CONS AS (SELECT CONSEGNA.AID, MAX(NUMCONSEGNE) AS MAX_CONS
                      FROM CONSEGNA
                      GROUP BY CONSEGNA.AID)

SELECT CONS.AID, CONS.FID
FROM CONSEGNA CONS
WHERE CONS.NUMCONSEGNE = (SELECT MAX_CONS
                          FROM A_F_TOT_CONS
                          WHERE CONS.AID = A_F_TOT_CONS.AID);


SELECT MULTE.FID, FATTORINO.NOME, SUM(COSTO) AS TOT_COSTO
FROM MULTE, FATTORINO
WHERE MULTE.FID = FATTORINO.FID
GROUP BY MULTE.FID, FATTORINO.NOME
HAVING SUM(COSTO) > (SELECT AVG(COSTO)
                   FROM MULTE)


SELECT CONSEGNA.FID, SUM(NUMCONSEGNE) + SUM(NUMRITIRI)
FROM CONSEGNA
GROUP BY CONSEGNA.FID
HAVING SUM(NUMCONSEGNE) + SUM(NUMRITIRI) > 0 
       AND COUNT(*) = (SELECT COUNT(*)
                       FROM AZIENDA)


SELECT CONSEGNE_FOR_AID_AND_SESSO.AID, CONSEGNA.FID, CONSEGNE_FOR_AID_AND_SESSO.SESSO, CONSEGNE_FOR_AID_AND_SESSO.MAX_CONS
FROM (SELECT AID, FATTORINO.SESSO, MAX(NUMCONSEGNE) AS MAX_CONS
      FROM CONSEGNA, FATTORINO
      WHERE CONSEGNA.FID = FATTORINO.FID
      GROUP BY AID, FATTORINO.SESSO
      HAVING MAX(NUMCONSEGNE) > 0) CONSEGNE_FOR_AID_AND_SESSO, CONSEGNA
WHERE CONSEGNE_FOR_AID_AND_SESSO.MAX_CONS = CONSEGNA.NUMCONSEGNE
