SELECT *
FROM FATTORINO;


SELECT DISTINCT AID
FROM CONSEGNA;


SELECT NOME, FID
FROM FATTORINO
WHERE NOME LIKE 'B%';


SELECT NOME, SESSO, FID
FROM FATTORINO
WHERE TEL <> 8467 OR TEL IS NULL;


SELECT NOME, CITTA
FROM FATTORINO, MULTE
WHERE FATTORINO.FID = MULTE.FID;


SELECT FATTORINO.NOME
FROM FATTORINO, CONSEGNA
WHERE (FATTORINO.CITTA = 'Inglewood' OR FATTORINO.CITTA = 'Stratford') AND FATTORINO.FID = CONSEGNA.FID
GROUP BY FATTORINO.FID, FATTORINO.NOME
HAVING COUNT(*) > 1;


SELECT FATTORINO.FID, SUM(MULTE.COSTO) AS TOT_COSTO
FROM FATTORINO, MULTE
WHERE FATTORINO.CITTA = 'Inglewood' AND FATTORINO.FID = MULTE.FID
GROUP BY FATTORINO.FID
HAVING COUNT(*) > 1;


SELECT FATTORINO.FID, FATTORINO.NOME, FATTORINO.INIZIALI
FROM FATTORINO
WHERE FATTORINO.FID NOT IN (SELECT MULTE.FID FROM MULTE);


SELECT FATTORINO.FID
FROM FATTORINO
WHERE FATTORINO.FID IN (SELECT MULTE.FID 
                        FROM MULTE 
                        WHERE MULTE.COSTO = 25)
      AND FATTORINO.FID IN (SELECT MULTE.FID 
                        FROM MULTE 
                        WHERE MULTE.COSTO = 30);


SELECT MAX(COUNT(*))
FROM MULTE
GROUP BY MULTE.FID, MULTE.DATA;


SELECT AVG(SUM(MULTE.COSTO))
FROM MULTE
GROUP BY MULTE.FID;


WITH A_F_TOT_CONS AS (SELECT CONSEGNA.AID, MAX(NUMCONSEGNE) AS MAX_CONS
                      FROM CONSEGNA
                      GROUP BY CONSEGNA.AID)

SELECT CONS.AID, CONS.FID
FROM CONSEGNA CONS
WHERE CONS.NUMCONSEGNE = (SELECT MAX_CONS
                          FROM A_F_TOT_CONS
                          WHERE CONS.AID = A_F_TOT_CONS.AID);


SELECT MULTE.FID, FATTORINO.NOME, SUM(COSTO) AS TOT_COSTO
FROM MULTE, FATTORINO
WHERE MULTE.FID = FATTORINO.FID
GROUP BY MULTE.FID, FATTORINO.NOME
HAVING SUM(COSTO) > (SELECT AVG(COSTO)
                   FROM MULTE)


SELECT CONSEGNA.FID, SUM(NUMCONSEGNE) + SUM(NUMRITIRI)
FROM CONSEGNA
GROUP BY CONSEGNA.FID
HAVING SUM(NUMCONSEGNE) + SUM(NUMRITIRI) > 0 
       AND COUNT(*) = (SELECT COUNT(*)
                       FROM AZIENDA)


SELECT CONSEGNE_FOR_AID_AND_SESSO.AID, CONSEGNA.FID, CONSEGNE_FOR_AID_AND_SESSO.SESSO, CONSEGNE_FOR_AID_AND_SESSO.MAX_CONS
FROM (SELECT AID, FATTORINO.SESSO, MAX(NUMCONSEGNE) AS MAX_CONS
      FROM CONSEGNA, FATTORINO
      WHERE CONSEGNA.FID = FATTORINO.FID
      GROUP BY AID, FATTORINO.SESSO
      HAVING MAX(NUMCONSEGNE) > 0) CONSEGNE_FOR_AID_AND_SESSO, CONSEGNA
WHERE CONSEGNE_FOR_AID_AND_SESSO.MAX_CONS = CONSEGNA.NUMCONSEGNE


SELECT FATTORINO.NOME, FATTORINO.INIZIALI
FROM MULTE, FATTORINO
WHERE MULTE.DATA > TO_DATE('31/12/2000','DD/MM/YYYY') AND MULTE.FID = FATTORINO.FID
GROUP BY MULTE.FID, FATTORINO.NOME, FATTORINO.INIZIALI
ORDER BY FATTORINO.NOME


SELECT CONSEGNA.AID, CONSEGNA.FID
FROM CONSEGNA, FATTORINO
WHERE NUMCONSEGNE >= 1 AND NUMRITIRI >= 2 AND FATTORINO.CITTA = 'Stratford' AND FATTORINO.FID = CONSEGNA.FID


SELECT FATTORINO.FID
FROM FATTORINO, CONSEGNA, AZIENDA
WHERE FATTORINO.ANNO_NASCITA > 1982 
      AND CONSEGNA.NUMCONSEGNE >= 1 AND CONSEGNA.FID = FATTORINO.FID
      AND AZIENDA.INCARICO = 'primo' AND AZIENDA.AID = CONSEGNA.AID
ORDER BY FATTORINO.FID DESC


SELECT FATTORINO.NOME, MIN(MULTE.COSTO)
FROM MULTE, FATTORINO
WHERE MULTE.FID = FATTORINO.FID
GROUP BY MULTE.FID, FATTORINO.NOME
HAVING COUNT(*) >= 2 AND COUNT(*) <= 4


SELECT CONSEGNA.FID, CONSEGNA.NUMCONSEGNE, CONSEGNA.NUMRITIRI
FROM CONSEGNA, FATTORINO
WHERE FATTORINO.NOME LIKE 'B%' AND FATTORINO.CITTA <> 'Stratford' AND FATTORINO.FID = CONSEGNA.FID


SELECT CONSEGNA.FID
FROM CONSEGNA
WHERE CONSEGNA.NUMCONSEGNE + CONSEGNA.NUMRITIRI > 0
      AND CONSEGNA.AID IN (SELECT CONSEGNA.AID
                           FROM CONSEGNA
                           WHERE CONSEGNA.NUMCONSEGNE > 0 AND CONSEGNA.FID = 57)


SELECT MULTE.FID, MIN(MULTE.DATA), MAX(MULTE.DATA)
FROM MULTE
GROUP BY MULTE.FID
HAVING COUNT(*) >= 2


WITH MEDIA_ANNO(ANNO, MEDIA) AS (SELECT EXTRACT(YEAR FROM MULTE.DATA), AVG(MULTE.COSTO)
                    FROM MULTE
                    GROUP BY EXTRACT(YEAR FROM MULTE.DATA))

SELECT MULTE.MID, MULTE.DATA, MULTE.COSTO
FROM MULTE, MEDIA_ANNO
WHERE MEDIA_ANNO.ANNO = EXTRACT(YEAR FROM MULTE.DATA) AND MULTE.COSTO > MEDIA_ANNO.MEDIA


WITH CITTA_AVG(CITTA, MEDIA) AS (SELECT FATTORINO.CITTA, AVG(CONSEGNA.NUMCONSEGNE)
				 FROM CONSEGNA, FATTORINO
				 WHERE CONSEGNA.FID = FATTORINO.FID
				 GROUP BY FATTORINO.CITTA),

     FATTORINO_TOT(FID, TOT_CONS) AS (SELECT CONSEGNA.FID, SUM(CONSEGNA.NUMCONSEGNE)
				      FROM CONSEGNA
				      GROUP BY CONSEGNA.FID)

SELECT CITTA_AVG.CITTA
FROM CITTA_AVG
WHERE CITTA_AVG.MEDIA < (SELECT AVG(TOT_CONS)
                         FROM FATTORINO_TOT);


WITH FID_AVG_RITIRI(FID, MEDIA_RITIRI) AS (SELECT CONSEGNA.FID, AVG(CONSEGNA.NUMRITIRI)
					   FROM CONSEGNA
					   GROUP BY CONSEGNA.FID)
                        
SELECT FATTORINO.ANNO_NASCITA
FROM FID_AVG_RITIRI, FATTORINO
WHERE FID_AVG_RITIRI.MEDIA_RITIRI = (SELECT MAX(FID_AVG_RITIRI.MEDIA_RITIRI)
                                     FROM FID_AVG_RITIRI)
      AND FID_AVG_RITIRI.FID = FATTORINO.FID;


WITH FID_SESSO_TOT_MULTE(FID, SESSO, TOT_MULTE) AS (SELECT MULTE.FID, FATTORINO.SESSO, COUNT(*)
						    FROM MULTE, FATTORINO
						    WHERE MULTE.FID = FATTORINO.FID
						    GROUP BY MULTE.FID)
                                                    
SELECT FID_SESSO_TOT_MULTE.SESSO, FID_SESSO_TOT_MULTE.TOT_MULTE
FROM FID_SESSO_TOT_MULTE
WHERE FID_SESSO_TOT_MULTE.TOT_MULTE = (SELECT MAX(X.TOT_MULTE)
                                       FROM FID_SESSO_TOT_MULTE X);


WITH FID_SESSO_TOT(FID, SESSO, TOT_CONS) AS (SELECT CONSEGNA.FID, FATTORINO.SESSO, SUM(CONSEGNA.NUMCONSEGNE)
	  				     FROM FATTORINO, CONSEGNA
				             WHERE FATTORINO.FID = CONSEGNA.FID
	  				     GROUP BY CONSEGNA.FID)

SELECT FID_SESSO_TOT.SESSO, FID_SESSO_TOT.TOT_CONS
FROM FID_SESSO_TOT
WHERE FID_SESSO_TOT.TOT_CONS = (SELECT MAX(X.TOT_CONS)
                               	FROM FID_SESSO_TOT X);
