CREATE TRIGGER change_salary
AFTER UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN :OLD.DNAME = "ACCOUNTING" AND :NEW.DNAME = "SALES"
BEGIN

    UPDATE IMP
    SET IMP.SAL = IMP.SAL + 100
    WHERE IMP.DEPTNO = :OLD.DEPTNO;

END;